### ISSUE TITLE
"Error: Unknown message digest" when using crypto.subtle.verify({'name':'ECDSA', 'hash':'SHA-256'}, ...)

### ISSUE THREAD

**Issue by Jonas-Metzger** [crypto-browserify/crypto-browserify#203]
I'm trying to bundle the PageSigner [pgsg-node.js](https://github.com/tlsnotary/pagesigner/blob/master/webextension/content/pgsg-node/pgsg-node.js) (written in NodeJS) using browserify, such that I can run it via QuickJS and eventually compile it to WASM.

After some minor edits to the code, I managed to successfully execute both `node bundle.js` and the QuickJS analogue `qjs bundle.js`. However, that only works if I remove [this crucial line](https://github.com/tlsnotary/pagesigner/blob/4e437d0be7ef91af3beb156a81a4aade1d20c1b1/webextension/content/tlsn.js#L634):

```
var result = await crypto.subtle.verify({'name':'ECDSA', 'hash':'SHA-256'}, notary_pk_CryptoKey, ba2ab(sig_p1363), ba2ab(signed_data_ba))
```

and replace it with `var result = true`. Otherwise I get the following error after executing `node bundle.js`:

```
Error: Unknown message digest
    at new Verify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:13849:20)
    at Object.createVerify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:13882:10)
    at Function.verify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:33318:51)
    at EcdsaProvider.onVerify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:33496:25)
    at EcdsaProvider.verify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:82175:30)
    at SubtleCrypto.verify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:82832:39)
    at verifyNotarySig (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:2724:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async verifyPgsgV4 (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:723:10)
    at async Object.verifyPgsg (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:661:12) Error
(node:7830) UnhandledPromiseRejectionWarning: Error: Unknown message digest
    at new Verify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:13849:20)
    at Object.createVerify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:13882:10)
    at Function.verify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:33318:51)
    at EcdsaProvider.onVerify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:33496:25)
    at EcdsaProvider.verify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:82175:30)
    at SubtleCrypto.verify (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:82832:39)
    at verifyNotarySig (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:2724:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async verifyPgsgV4 (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:723:10)
    at async Object.verifyPgsg (/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/bundle.js:661:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7830) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7830) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What's weird is that at least some of the `crypto.subtle` functionality works, the[ line right before](https://github.com/tlsnotary/pagesigner/blob/4e437d0be7ef91af3beb156a81a4aade1d20c1b1/webextension/content/tlsn.js#L632)
```
var notary_pk_CryptoKey = await crypto.subtle.importKey(
      "raw", ba2ab(notaryPubkey_ba), {name: 'ECDSA', namedCurve:'P-256'}, true, ["verify"]);
```
works flawlessly. Also, executing my modified unbundled file `node pgsg-node.js` does not produce this error.

**Comment by Jonas-Metzger** [comment]
With [some help](https://github.com/PeculiarVentures/webcrypto/issues/32) from the @peculiar/webcrypto repo (which I have use to replace the webcrypto API given my bundle will not run in a browser), it seems that the error is coming [from this line in their crypto.ts](https://github.com/PeculiarVentures/webcrypto/blob/7a3f11f3fd7df282084ce377d4be2e3b8b7ac118/src/mechs/ec/crypto.ts#L74):

```
public static async verify(algorithm: EcdsaParams, key: EcPublicKey, signature: Uint8Array, data: Uint8Array): Promise<boolean> {
    const cryptoAlg = (algorithm.hash as Algorithm).name.replace("-", "");
    const signer = crypto.createVerify(cryptoAlg);
```

which is meant to call NodeJS crypto API, but now calls crypto-browserify. Tracing the call through browserify-sign/index.js, it probably arises on [this line](https://github.com/crypto-browserify/browserify-sign/blob/266b780b8ab112bd12e4ef330d9b4a65b76350e7/browser/index.js#L51)

```
function Verify (algorithm) {
  stream.Writable.call(this)

  var data = algorithms[algorithm]
  if (!data) throw new Error('Unknown message digest')
```

Does this mean that ESCDA is not supported? Or is `algorithm` (I'm assuming a string?) formatted in the wrong way? How should it be formatted?
